### ISSUE TITLE
Angle Section background

### ISSUE THREAD

**Issue by bstopp** [hlxsites/takeda-ihs#11]
<img width="861" alt="Angle_Background" src="https://github.com/hlxsites/takeda-ihs/assets/6520270/3c9b4c99-3061-49d7-8374-000d51f7f0a8">

**Comment by lwintch** [comment]
The main mechanic for this is a `clip-path` which requires space between the lower and upper vertical limits between the content in the section for the angle line to run through.  Otherwise, this effect cuts out content such as this.

![image](https://github.com/hlxsites/takeda-ihs/assets/5343448/4bc5cd7a-f699-45c9-b9d9-52a16e281e5c)

We can decorate the section and add 2 blocks (they don't have to be custom blocks, just ends up with a div having a certain css classname) to get this effect, if we add padding between the content blocks in the section.  This seems less than optimal, but we'd have to guarantee there is enough space between the content where the angle effect runs through.

![image](https://github.com/hlxsites/takeda-ihs/assets/5343448/e8050f17-21bb-48e1-8d12-d60c4d0c732b)

We could use another approach with JS, but we would probably still need to decorate content in the section to mark where to add the dividing space and draw the angle effect.

**Comment by bstopp** [comment]
> We could use another approach with JS, but we would probably still need to decorate content in the section to mark where to add the dividing space and draw the angle effect.

I think this is our best bet. We pick either `Background angle: before` or `Background angle: end` as a Section metadata attribute. we should be able to add a `::before/::after` pseudo element to the first/last wrapper of that section, which will contain padding and draw the angle

Thoughts?

**Comment by lwintch** [comment]
> > We could use another approach with JS, but we would probably still need to decorate content in the section to mark where to add the dividing space and draw the angle effect.
> 
> I think this is our best bet. We pick either `Background angle: before` or `Background angle: end` as a Section metadata attribute. we should be able to add a `::before/::after` pseudo element to the first/last wrapper of that section, which will contain padding and draw the angle
> 
> Thoughts?

Same.  I implemented this using the strategy we discussed in Slack.
